### ISSUE TITLE
What is this app all about?

### ISSUE THREAD

**Issue by ancoreraj** [Pingoo-techie/neboola#2]
I also want to contribute to it.

**Comment by deepraj1729** [comment]
Hi @ancoreraj , this is an app that we are building for NIT Agartala students. It's an all in one app that students can use.
The features cant be revealed as of now. You will see once the first release is launched

**Comment by hkm007** [comment]
Hey @ancoreraj, Let's connect and discuss a bit more on this.
Give us your contact details.

**Comment by hkm007** [comment]
> I also want to contribute to it.

Hey @ancoreraj, Let's connect and discuss a bit more on this.
Give us your contact details.

**Comment by ancoreraj** [comment]
@hkm007 , Whatsapp no- 9507191293
